spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: Kundan@1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:ondeyostephen0@gmail.com}
    password: ${MAIL_PASSWORD:yvhc ebmf dacy tfdz}
    from: ${MAIL_FROM:ondeyostephen0@gmail.com}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB


jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890123456789012345678901234567890}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:86400000} #24 hours
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000} #7 days


app:
  name: ${APP_NAME:safari_store}
  version: 1.0.0
  api:
    version: v1
    base-path: /api/v1

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# OpenAPI/Swagger Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
  packages-to-scan: com.kenamart.ecommerce.controller
  paths-to-match: /api/v1/**